import React from 'react'
import Head from 'next/head'
import { Container, AppBar, Toolbar } from '@mui/material'
import AddTodo from '@/components/AddTodo'
import TodoList from '@/components/TodoList'

export default function Home() {

  return (
    <>
      <Head>
        <title>Todolist-Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '50px 0 0 0' }}>
        <AppBar position="fixed">
          <Toolbar>Todo List</Toolbar>
        </AppBar>
        <Toolbar />
        <Container maxWidth="lg">
          <AddTodo />
          <TodoList />
        </Container>
      </main>
    </>
  )
}
